### ISSUE TITLE
[enhancement] Alchemy logo color in terminal 

### ISSUE THREAD

**Issue by technophile-04** [Eversmile12/create-web3-dapp#10]
Change the color of the Alchemy logo to blue while scaffolding the `create-web3-daap`

Before : 

<img width="1158" alt="screenshot_2" src="https://user-images.githubusercontent.com/80153681/183491900-3c100f8b-8c15-458b-8b5a-8307075099c0.png">

After : 

![Screenshot 2022-08-09 at 12 22 07 AM](https://user-images.githubusercontent.com/80153681/183492381-e64bab35-a0d0-42f2-be31-65601e307e83.jpg)

**Comment by dicethedev** [comment]
I love it with the blue color. Nice one from there.

**Comment by technophile-04** [comment]
I am also working on adding the gradient to the logo in terminal just like the original logo

**Comment by Eversmile12** [comment]
This is amazing! Merging!
