### ISSUE TITLE
Add click events

### ISSUE THREAD

**Issue by kunal232i** [Eversmile12/create-web3-dapp#12]
![image](https://user-images.githubusercontent.com/81668653/183579873-3e899a92-3be7-402c-b504-c54eed3b4b1a.png)

Add click events for "**Go there**"

**Comment by MujahidAli954** [comment]
I want to work on this

**Comment by Eversmile12** [comment]
@MujahidAli954 Let's do it!

**Comment by sanketsaagar** [comment]
I also want to work, Looking forward.

**Comment by MujahidAli954** [comment]
> @MujahidAli954 Let's do it!

 when I add click events which functionalities  I can perform inside click event. OR simply goes to another page or alert box only trigger. kindly guide me

**Comment by MujahidAli954** [comment]
> @MujahidAli954 Let's do it!

 when I add click events which functionalities  I can perform inside click event. OR simply goes to another page or alert box only trigger. kindly guide me

**Comment by Eversmile12** [comment]
Released in latest commit
