### ISSUE TITLE
Discord join link error '404'

### ISSUE THREAD

**Issue by Lavishq** [Eversmile12/create-web3-dapp#14]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/96654752/183587926-98db33fb-7ef8-4217-b37e-0afbaac8e3a1.png">

**Comment by Eversmile12** [comment]
Just merged in [0d0a35c](https://github.com/rkueny/create-web3-dapp/commit/0d0a35c21fef237ad20b09c558b459abe860eae3)

**Comment by Lavishq** [comment]
It is still 404

**Comment by Lavishq** [comment]
> Just merged in [0d0a35c](https://github.com/rkueny/create-web3-dapp/commit/0d0a35c21fef237ad20b09c558b459abe860eae3)

It is still 404
