### ISSUE TITLE
AlchemySDK link in README

### ISSUE THREAD

**Issue by technophile-04** [Eversmile12/create-web3-dapp#2]
It seems that the AlchemySDK reference to docs link is not working. 
Under the sections : 
`Complementary Docs`
https://github.com/Eversmile12/create-web3-dapp/blob/main/README.md#complementary-docs

**Comment by Eversmile12** [comment]
Merged! Thanks!

**Comment by EjayGit** [comment]
Thanks to you too Vitto!

Sent from my iPhone

On 9 Aug 2022, at 00:29, VItto Rivabella ***@***.***> wrote:

﻿

Merged! Thanks!
