### ISSUE TITLE
Some enhancements I would like to suggest.

### ISSUE THREAD

**Issue by kenryu42** [Eversmile12/create-web3-dapp#29]
### Enhancements

1. Remove the quotes from `hardhat.config.js` when generating instead of having users remove it manually.
2. Add `next.config.js` to the template and enable Strict Mode.
https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode 
3. Implement the Next.js Api route in the template to avoid alchemy api key being leaked to the client-side.

I could implement the enhancements. Let me know what you guys think.

**Comment by Eversmile12** [comment]
This sounds amazing! Definitely, pelase go ahead!

**Comment by Eversmile12** [comment]
> ### Enhancements
> 1. Remove the quotes from `hardhat.config.js` when generating instead of having users remove it manually.

This has been resolved!

**Comment by Eversmile12** [comment]
solved
