### ISSUE TITLE
Text need to be different

### ISSUE THREAD

**Issue by kanishak11-cyber** [Eversmile12/create-web3-dapp#8]
![image](https://user-images.githubusercontent.com/84625838/183481403-cd63c267-321e-470f-8535-16cb6348bc4f.png)

all 4 part have same description , need to be changed

**Comment by kunal232i** [comment]
I would like to help with this issue.

**Comment by Eversmile12** [comment]
That would be amazing @kunal232i - we need to list Alchemy resources there and vary them based on the chain selected!

**Comment by dicethedev** [comment]
@Eversmile12 can you make those description translated to English and simple to read and understand.

**Comment by sanketsaagar** [comment]
Also @Eversmile12 , We can make the "Go there" button little 3D.

**Comment by kanishak11-cyber** [comment]
I also want to work on this Issue @Eversmile12 
I'll create more issue in which i can contribute

**Comment by Eversmile12** [comment]
> @Eversmile12 can you make those descriptions translated to English and make simple to read and understand?

@dicethedev that's just placeholder text - we're currently creating the copy! 



> Also @Eversmile12 , We can make the "Go there" button little 3D.

Yes! We need to create the style guidelines based on the alchemy.com brand! 



> I also want to work on this Issue @Eversmile12 I'll create more issue in which i can contribute

Amazing! Can't wait!

**Comment by dicethedev** [comment]
@Eversmile12 ok that is cool.

**Comment by Eversmile12** [comment]
Resolved in latest commit
